# Generated by Django 4.2.5 on 2023-09-27 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('calories', models.IntegerField(default=0, verbose_name='калорий на 100 гр.')),
                ('proteins', models.IntegerField(default=0, verbose_name='белков на 100 гр.')),
                ('fats', models.IntegerField(default=0, verbose_name='жиров на 100 гр.')),
                ('carbohydrates', models.IntegerField(default=0, verbose_name='углеводов на 100 гр.')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='срок')),
                ('breakfasts', models.BooleanField(db_index=True, default=True, verbose_name='завтраки')),
                ('lunches', models.BooleanField(db_index=True, default=True, verbose_name='обеды')),
                ('dinners', models.BooleanField(db_index=True, default=True, verbose_name='ужины')),
                ('desserts', models.BooleanField(db_index=True, default=True, verbose_name='десерты')),
                ('persons_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='количество персон')),
                ('allergies', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Рыба и морепродукты'), (2, 'Мясо'), (3, 'Зерновые'), (4, 'Продукты пчеловодства'), (5, 'Орехи и бобовые'), (6, 'Молочные продукты')], max_length=11)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='промокод')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'тарифы',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото')),
                ('meal_time', models.CharField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('DESSERT', 'Десерт')], max_length=10, verbose_name='время приема пищи')),
                ('type', models.CharField(choices=[('CLASSIC', 'Классическое'), ('LOW_CARB', 'Низкоуглеводное'), ('VEGETARIAN', 'Вегетарианское'), ('KETO', 'Кето')], default='CLASSIC', max_length=30, verbose_name='тип меню')),
                ('calories', models.IntegerField(default=0, verbose_name='калорий на 100 гр.')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='описание')),
                ('relevance', models.BooleanField(db_index=True, default=True, verbose_name='актуальность')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='вес')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='foodplan.ingredient', verbose_name='ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='foodplan.recipe', verbose_name='рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата и время заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodplan.rate', verbose_name='тариф')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
