# Generated by Django 4.2.5 on 2023-09-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0002_alter_recipe_calories_alter_recipe_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(choices=[('завтрак', 'завтрак'), ('обед', 'обед'), ('ужин', 'ужин'), ('десерт', 'десерт')], max_length=10, verbose_name='время приема пищи'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('классическое', 'классическое'), ('низкоуглеводное', 'низкоуглеводное'), ('вегетарианское', 'вегетарианское'), ('кето', 'кето')], default='классическое', max_length=30, verbose_name='тип меню'),
        ),
    ]
