# Generated by Django 4.2.5 on 2023-09-28 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodplan', '0003_alter_recipe_meal_time_alter_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('классическое', 'классическое'), ('низкоуглеводное', 'низкоуглеводное'), ('вегетарианское', 'вегетарианское'), ('кето', 'кето')], default='классическое', max_length=30, verbose_name='тип меню'),
        ),
    ]
