# Generated by Django 4.2.5 on 2023-10-01 19:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0004_order_client_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Рыба и морепродукты'), (2, 'Мясо'), (3, 'Зерновые'), (4, 'Продукты пчеловодства'), (5, 'Орехи и бобовые'), (6, 'Молочные продукты')], max_length=11, null=True, verbose_name='противопоказания (аллергии)'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Рыба и морепродукты'), (2, 'Мясо'), (3, 'Зерновые'), (4, 'Продукты пчеловодства'), (5, 'Орехи и бобовые'), (6, 'Молочные продукты')], max_length=11, null=True, verbose_name='наличие аллергии'),
        ),
    ]
